version: '3.3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file:
      - path: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - path: ../.env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/app/result_build/build/
  gateway:
    build: .
    ports:
      - 80:80
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend
