version: '3.3'

volumes:
  static_media:

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static_media:/app/result_build/
  nginx:
    build: .
    ports:
      - 80:80
    volumes:
      - static_media:/staticfiles/
