# Generated by Django 3.2.16 on 2024-04-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240406_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes_ingredients',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_amount', to='recipes.recipes'),
        ),
    ]
