# Generated by Django 3.2.16 on 2024-05-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='follow',
            new_name='following',
        ),
    ]
