# Generated by Django 3.2.16 on 2024-03-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240326_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
